---
# vars file for jinja2_spine
  eos_provider:
    username: "{{ ansible_user }}"
    password: "{{ ansible_pwd }}"
    timeout: 100
    host: "{{ inventory_hostname }}"
  rid: router_id
  asn: 65000
  bgp_neighbors:
  -  remote_as: 65001
     neighbor: 172.31.1.1
  -  remote_as: 65001
     neighbor: 172.31.1.7 
  -  remote_as: 65002
     neighbor: 172.31.1.3
  -  remote_as: 65002
     neighbor: 172.31.1.5 
  L3_interfaces:
  -  interface: Ethernet 1
  -  interface: Ethernet 2
  -  interface: Ethernet 3
  -  interface: loopback 0
  -  interface: loopback 1