---
# vars file for jinja2_spine
  eos_provider:
    username: "{{ ansible_user }}"
    password: "{{ ansible_pwd }}"
    timeout: 100
    host: "{{ inventory_hostname }}"
  device_name: hostname
  asn: 65001
  bgp_neighbors:
  - { remote_as: 65100, neighbor: 172.31.1.1 }
  - { remote_as: 65002, neighbor: 172.31.1.3 }
  L3_interfaces:
  -  { interface: Ethernet1 }
     { Ethernet1: Ethernet1 }|
  -  { interface: Ethernet2 } 
     { Ethernet2: Ethernet2 }
  -  interface: loopback 0 
  -  interface: loopback 1
 
