---
# tasks file for spine
  - name: Generate Spine Config
    template: src=spine.j2 dest=roles/jinja2_spine/files/{{inventory_hostname}}.cfg
  - name: Push Config from configs Folder
    eos_config:
       src: roles/jinja2_spine/files/{{inventory_hostname}}.cfg
       replace: 'config'
       provider: "{{ eos_provider }}"
  - name: Save configuration to startup config
    eos_config:
        save_when: always


